### ISSUE TITLE
Please specify licenses for this demo program

### ISSUE THREAD

**Issue by smoriemb** [hirotakaster/PIDcontroll#1]
Could you kindly specify what licenses we could choose when we reuse this demo program for another project.

**Comment by hirotakaster** [comment]
Hi @smoriemb ,
This repo source code is just an sample code.

**Comment by hirotakaster** [comment]
Hi @smoriemb ,
This repo source code is just an sample code for the [inverted pendulum](http://www.hirotakaster.com/?p=3576) (sorry written in japanease my blog). so, You could use this code freely. If I dare put a license on this, it is MIT.
Thank you.

**Comment by smoriemb** [comment]
@hirotakaster 
Thanks for your specifying license.

Actually, I've ported your code to MBed environment using ROS2 message communication, as below. 
https://twitter.com/takasehideki/status/1584488359808102402

Given your code, I was able to implement our demonstration very quickly.
